#!/bin/bash
shopt -s expand_aliases
module load tapir
module load parallel

DIRECTORY=${1:-"../data/intermediate/phylo_informativeness"}

"/bin/ls" "${DIRECTORY}/fasta/"*".fasta" | "parallel" 'perl ./convertfasta2nex.pl {} > {}.nex'

# remove and recreate nex directories
rm -r "${DIRECTORY}/nex"*

for file in $("/bin/ls" "${DIRECTORY}/fasta/"*".nex")
do
    mkdir -p "${DIRECTORY}/nex/${file}"
done

# move nex files to nex directories
for file in $("/bin/ls" "${DIRECTORY}/fasta/"*".nex")
do
    mv "${file}" "${DIRECTORY}/nex/${file}/"
done

# remove and recreate tapir ouput directories
rm -r "${DIRECTORY}/tapir_out"*

for file in $("/bin/ls" "${DIRECTORY}/fasta/"*".nex")
do
    mkdir -p "${DIRECTORY}/tapir_out/${file}"
done

#tapir_compute.py $DIRECTORY/nex/ ../input/959genes.phy.contree_AgeRooted_wholeNumbs.tre \
# --intervals=2-3,3-5,5-8,8-10,10-18 \
# --times=2,3,5,8,10,17 \
# --tree-format=newick \
# --output $DIRECTORY/tapir_out

"/bin/ls" "${DIRECTORY}/fasta/"*".nex" | \
parallel "tapir_compute.py" "${DIRECTORY}/nex/{}/" "../data/input/959genes.phy.contree_AgeRooted_wholeNumbs.tre" \
--intervals=2-3,3-5,5-8,8-10,10-18 \
--times=2,3,5,8,10,17 --tree-format=newick \
--output "${DIRECTORY}/tapir_out/{}"

# collect output
rm -r "${DIRECTORY}/sql"
mkdir -p "${DIRECTORY}/sql"

for file in $("/bin/ls" "${DIRECTORY}/fasta/"*".nex")
do
    mv "${DIRECTORY}/tapir_out/${file}/"*".sqlite" "${DIRECTORY}/sql/${file}.sqlite"
done
